# This file was generated by GoReleaser. DO NOT EDIT.
cask "parlay" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/ddwht/parlay/releases/download/v#{version}/parlay_Darwin_x86_64.tar.gz"
      sha256 "87bbac50795432bf58f1b311c035b9cd14c300e7943262645e202c79b125cc58"
    end
    on_arm do
      url "https://github.com/ddwht/parlay/releases/download/v#{version}/parlay_Darwin_arm64.tar.gz"
      sha256 "799a0e19c59b51d9f638a87c546d048a7bc766791e1f6f51d0c26a8f6b2c0557"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ddwht/parlay/releases/download/v#{version}/parlay_Linux_x86_64.tar.gz"
      sha256 "49d231db3657ce2171b730b10bdc81b89c2b06dd6fd42d7d178f7f1c94e6f98e"
    end
    on_arm do
      url "https://github.com/ddwht/parlay/releases/download/v#{version}/parlay_Linux_arm64.tar.gz"
      sha256 "bd54bc036f83614ff953d2610c5209694152d3806e1b7fc12cf9a568736bb86c"
    end
  end

  name "parlay"
  desc "Intent-driven specification framework"
  homepage "https://github.com/ddwht/parlay"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parlay"

  # No zap stanza required

end
