# This file was generated by GoReleaser. DO NOT EDIT.
cask "parlay" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/ddwht/parlay/releases/download/v#{version}/parlay_Darwin_x86_64.tar.gz"
      sha256 "f337c98794a42c27e0e2cb564b83363b756b914249b785be64e9d54747eb41f9"
    end
    on_arm do
      url "https://github.com/ddwht/parlay/releases/download/v#{version}/parlay_Darwin_arm64.tar.gz"
      sha256 "7dea0daacd96cc771612687e831778a2830b8fe6f0ab193502353d5ffa837591"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ddwht/parlay/releases/download/v#{version}/parlay_Linux_x86_64.tar.gz"
      sha256 "a70bc78a08a99b30e6e6ad452e66bdd0192fe380d246c313281800986078e43c"
    end
    on_arm do
      url "https://github.com/ddwht/parlay/releases/download/v#{version}/parlay_Linux_arm64.tar.gz"
      sha256 "968f813a738f567bdb0fdb307fecca16ddcb7448c90dab1e736f4f5e1116a3e8"
    end
  end

  name "parlay"
  desc "Intent-driven specification framework"
  homepage "https://github.com/ddwht/parlay"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parlay"

  # No zap stanza required

end
