# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parlay < Formula
  desc "Intent-driven specification framework"
  homepage "https://github.com/ddwht/parlay"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddwht/parlay/releases/download/v0.2.0/parlay_Darwin_x86_64.tar.gz"
      sha256 "8765ac8c99cc9fc738818315e792d9d9d696fa6ee00ffae2b2f1c7e6bf544ca7"

      define_method(:install) do
        bin.install "parlay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddwht/parlay/releases/download/v0.2.0/parlay_Darwin_arm64.tar.gz"
      sha256 "c703ff5bdd6e99bbd125cb875e28a97b47882fedd2b29b1c44c715ac518d4c63"

      define_method(:install) do
        bin.install "parlay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddwht/parlay/releases/download/v0.2.0/parlay_Linux_x86_64.tar.gz"
      sha256 "efcc6a193f7b13c32809f3ecebebc48ff34c217ffd30e002a2d05d6dcecf619d"
      define_method(:install) do
        bin.install "parlay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddwht/parlay/releases/download/v0.2.0/parlay_Linux_arm64.tar.gz"
      sha256 "ef1082750ffaca3955f728b04948d94b00f4d8edd7d56e6462e501c39c6d610b"
      define_method(:install) do
        bin.install "parlay"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/parlay version")
  end
end
