# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parlay < Formula
  desc "Intent-driven specification framework"
  homepage "https://github.com/ddwht/parlay"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddwht/parlay/releases/download/v0.2.3/parlay_Darwin_x86_64.tar.gz"
      sha256 "15f13981771a7c5b91ba485974044deea494279b57ff09b8c5501cfb7f8bfce0"

      define_method(:install) do
        bin.install "parlay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddwht/parlay/releases/download/v0.2.3/parlay_Darwin_arm64.tar.gz"
      sha256 "2f189445ba7f234bd313120ec28e93f77b408a0eed05de4a9cf1d2d37beaedbd"

      define_method(:install) do
        bin.install "parlay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddwht/parlay/releases/download/v0.2.3/parlay_Linux_x86_64.tar.gz"
      sha256 "f43d852d5c339e3472cbb91cf73d130c7193e8d7a0e8ab50cc4dde3603f143da"
      define_method(:install) do
        bin.install "parlay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddwht/parlay/releases/download/v0.2.3/parlay_Linux_arm64.tar.gz"
      sha256 "2c7c842bd2fbe2c45dd9594299380430cfb29de151fdb120c484ef60639aa680"
      define_method(:install) do
        bin.install "parlay"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/parlay version")
  end
end
